# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/ctx.protoc

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='src/ctx.protoc',
  package='Easy.MakeContextualPrimary',
  serialized_pb=_b('\n\x0esrc/ctx.protoc\x12\x1a\x45\x61sy.MakeContextualPrimary\"\x15\n\x08\x66\x65\x61tures\x12\t\n\x01_\x18\x01 \x03(\x01\"\x11\n\x04pick\x12\t\n\x01_\x18\x01 \x02(\x03')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_FEATURES = _descriptor.Descriptor(
  name='features',
  full_name='Easy.MakeContextualPrimary.features',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='_', full_name='Easy.MakeContextualPrimary.features._', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=67,
)


_PICK = _descriptor.Descriptor(
  name='pick',
  full_name='Easy.MakeContextualPrimary.pick',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='_', full_name='Easy.MakeContextualPrimary.pick._', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=86,
)

DESCRIPTOR.message_types_by_name['features'] = _FEATURES
DESCRIPTOR.message_types_by_name['pick'] = _PICK

features = _reflection.GeneratedProtocolMessageType('features', (_message.Message,), dict(
  DESCRIPTOR = _FEATURES,
  __module__ = 'src.ctx.protoc_pb2'
  # @@protoc_insertion_point(class_scope:Easy.MakeContextualPrimary.features)
  ))
_sym_db.RegisterMessage(features)

pick = _reflection.GeneratedProtocolMessageType('pick', (_message.Message,), dict(
  DESCRIPTOR = _PICK,
  __module__ = 'src.ctx.protoc_pb2'
  # @@protoc_insertion_point(class_scope:Easy.MakeContextualPrimary.pick)
  ))
_sym_db.RegisterMessage(pick)


# @@protoc_insertion_point(module_scope)
